=== Vitilio/2021_LMSGI_VBR/Examen06/20210607EX06_VictorBlancoRodrigo/europa2020.dtd
<?xml version='1.0' encoding='UTF-8'?>


<!ELEMENT eurocopa (fasefinal)*>
<!ATTLIST eurocopa
    anyo (2020|2016|2012) #REQUIRED
    temporada (2021|2016|2012) #REQUIRED
  >
<!ELEMENT fasefinal (grupo)+>
<!ELEMENT grupo (seleccion)+>
<!ATTLIST grupo
    id ID  #REQUIRED
  >
<!ELEMENT seleccion (iniciales,clasificacion)*>
<!ELEMENT iniciales (ita|gal|sui|tur|bel|fin|din|rus|aus|pai|ucr|mac|rep|ing|cro|esc|esl|esp|sue|pol|por|fra|ale|hun)>
<!ELEMENT clasificacion (jugados,ganados,empatados,perdidos,golesfavor,golescontra)*>
<!ELEMENT jugados (#PCDATA)>
<!ELEMENT ganados (#PCDATA)>
<!ELEMENT empatados (#PCDATA)>
<!ELEMENT perdidos (#PCDATA)>
<!ELEMENT golesfavor (#PCDATA)>
<!ELEMENT golescontra (#PCDATA)>

=== Vitilio/2021_LMSGI_VBR/Examen06/20210607EX06_VictorBlancoRodrigo/europa2020.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE eurocopa SYSTEM 'europa2020.dtd'>
<eurocopa anyo="2020" temporada="2021" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="06.xsd">
	<fasefinal>
		<grupo id="A">
			<seleccion>
				<iniciales>ita</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>0</golescontra>
					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>gal</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>1</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>1</golesfavor>
					<golescontra>1</golescontra>
					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>sui</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>1</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>1</golesfavor>
					<golescontra>1</golescontra>
				</clasificacion>
			</seleccion>
			<seleccion >
				<iniciales>tur</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>3</golescontra>
				</clasificacion>
			</seleccion>
		</grupo>
		<grupo id="B">
			<seleccion >
				<iniciales>bel</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>0</golescontra>				
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>fin</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>0</golescontra>				
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>din</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>0</golescontra>				
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>rus</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>3</golescontra>
				</clasificacion>
			</seleccion>
		</grupo>
		<grupo id="C">
			<seleccion>
				<iniciales>aus</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>1</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>pai</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>2</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>ucr</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>2</golesfavor>
					<golescontra>3</golescontra>				
				</clasificacion>
			</seleccion>
			<seleccion >
				<iniciales>mac</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>1</golesfavor>
					<golescontra>3</golescontra>					
				</clasificacion>
			</seleccion>
		</grupo>
		<grupo id="D">
			<seleccion>
				<iniciales>rep</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>2</golesfavor>
					<golescontra>0</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>ing</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>1</golesfavor>
					<golescontra>0</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>cro</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>1</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>esc</iniciales>  
				<clasificacion>
					<jugados>0</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>1</golescontra>				
				</clasificacion>
			</seleccion>
		</grupo>
		<grupo id="E">
			<seleccion>
				<iniciales>esl</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>2</golesfavor>
					<golescontra>1</golescontra>				
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>esp</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>1</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>0</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>sue</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>1</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>0</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>pol</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>1</golesfavor>
					<golescontra>2</golescontra>					
				</clasificacion>
			</seleccion>
		</grupo>
		<grupo id="F">
			<seleccion>
				<iniciales>por</iniciales>  
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>3</golesfavor>
					<golescontra>0</golescontra>				
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>fra</iniciales>				
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>1</ganados>
					<empatados>0</empatados> 
					<perdidos>0</perdidos>
					<golesfavor>1</golesfavor>
					<golescontra>0</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>ale</iniciales>				
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>1</golescontra>					
				</clasificacion>
			</seleccion>
			<seleccion>
				<iniciales>hun</iniciales>				
				<clasificacion>
					<jugados>1</jugados> 
					<ganados>0</ganados>
					<empatados>0</empatados> 
					<perdidos>1</perdidos>
					<golesfavor>0</golesfavor>
					<golescontra>3</golescontra>					
				</clasificacion>
			</seleccion>
		</grupo>
	</fasefinal>
	
	</eurocopa>
