=== Vitilio/2021_LMSGI_VBR/EX02_20210309_VICTORBLANCORODRIGO/mapaestelar.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT mapaestelar (constelacion)>
<!ELEMENT constelacion (nombreespanol,superficie,estrellas,objetos,colindantes,observacion)>
<!ATTLIST constelacion
    nombreLatin CDATA #REQUIRED
  >
<!ELEMENT nombreespanol (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas
    numero_de_estrellas CDATA #REQUIRED
  >
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
    luminosidad CDATA #REQUIRED
  >
<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviademeteoros*)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviademeteoros (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT colindantes (nombres)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>

=== Vitilio/2021_LMSGI_VBR/EX02_20210309_VICTORBLANCORODRIGO/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapaestelar SYSTEM 'mapaestelar.dtd'> 
<mapaestelar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
             xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="Ursa Maior">
        <nombreespanol>La Osa Mayor</nombreespanol>
        <superficie>1279,7</superficie>
        <estrellas numero_de_estrellas="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="1,77">Alioth</masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
            <lluviademeteoros>
                <nombre>Kappa Ursa May贸ridas</nombre>
            </lluviademeteoros>
            <lluviademeteoros>
                <nombre>Lambda Ursa May贸ridas</nombre>
            </lluviademeteoros>
            <lluviademeteoros>
                <nombre>Psi Ursa May贸ridas</nombre>
            </lluviademeteoros>
            <lluviademeteoros>
                <nombre>Ursa May贸ridas de octubre</nombre>
            </lluviademeteoros>
        </objetos>
        <colindantes>
            <nombres>Bootes,Camelopardalis,Canes Venatici,Draco,Leo,Leo Minor,Lynx</nombres>
        </colindantes>
        <observacion>
            <hemisferio>Norte</hemisferio>
            <mes>04</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
</mapaestelar>
