<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail [
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA)>
    <!ELEMENT fecha EMPTY>
    <!ELEMENT fichero (#PCDATA)>
    <!ELEMENT mail (remitente, destinatario+, fecha, asunto?, mensaje?, fichero*)>
    <!ATTLIST  fecha dia CDATA  #REQUIRED
                      mes CDATA #REQUIRED
                      anyo CDATA   #REQUIRED>
    <!ATTLIST  fichero tipo  CDATA #IMPLIED>
    
]>

<mail>
     <remitente>perico@gmail.com</remitente>
    <destinatario>ambrosio@gmail.com</destinatario>
    <destinatario>meli@gmail.com</destinatario>
    <fecha dia="16" mes="01" anyo="2021"/>
    <asunto>Prueba de mensaje</asunto>
    <mensaje/>
    <fichero tipo="application/pdf">informe.pdf</fichero>
    <fichero tipo="image/jpeg"> foto.jpg</fichero>
</mail>

